name: openjmu_courses_web
description: A JMU courses Flutter Web application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.14.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dartx: ^0.3.0
  event_bus: 1.1.0
  flutter_spinkit: 4.1.1+1
  http: ^0.12.0+4
  oktoast: 2.3.1
  provider: 4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.16.1

flutter:
  uses-material-design: true
